name: Daily Naukri Automation Test

on:
  schedule:
    - cron: '30 3 * * *'  # Runs every day at 9:00 AM IST (3:30 AM UTC)
  workflow_dispatch:  # Allows manual execution from GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Chrome & ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable chromium-chromedriver
          echo "Chrome Version:"
          google-chrome --version
          echo "ChromeDriver Version:"
          chromedriver --version

      - name: Build and Run Tests
        run: mvn clean test
