name: Daily Naukri Automation Test

on:
  schedule:
    - cron: '30 3 * * *'  # Runs every day at 9:00 AM IST (3:30 AM UTC)
  workflow_dispatch:  # Allows manual execution from GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Chrome & ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          wget -q "https://chromedriver.storage.googleapis.com/${CHROME_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          echo "Google Chrome Version: $(google-chrome --version)"
          echo "ChromeDriver Version: $(chromedriver --version)"

      - name: Set ChromeDriver path
        run: echo "CHROMEWEBDRIVER=/usr/local/bin/chromedriver" >> $GITHUB_ENV

      - name: Run Tests
        run: mvn clean test -Dwebdriver.chrome.driver=$CHROMEWEBDRIVER
